---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: sriov-network-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operator-f0520
  namespace: sriov-network-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sriov-network-operator
  namespace: sriov-network-operator
spec:
  installPlanApproval: Automatic
  name: sriov-network-operator
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: local-storage-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage-operator-94f88
  namespace: local-storage-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: local-storage-operator
  namespace: local-storage-operator
spec:
  installPlanApproval: Automatic
  name: local-storage-operator
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: lvms-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator-b3404
  namespace: lvms-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: lvms-operator
  namespace: lvms-operator
spec:
  installPlanApproval: Automatic
  name: lvms-operator
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable-4.22

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: cluster-logging
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging-9d7a9
  namespace: cluster-logging
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cluster-logging
  namespace: cluster-logging
spec:
  installPlanApproval: Automatic
  name: cluster-logging
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable-6.5

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: ptp-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ptp-operator-824a8
  namespace: ptp-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ptp-operator
  namespace: ptp-operator
spec:
  installPlanApproval: Automatic
  name: ptp-operator
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: lifecycle-agent
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lifecycle-agent-c439d
  namespace: lifecycle-agent
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: lifecycle-agent
  namespace: lifecycle-agent
spec:
  installPlanApproval: Automatic
  name: lifecycle-agent
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: redhat-oadp-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-oadp-operator-57007
  namespace: redhat-oadp-operator
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: redhat-oadp-operator
  namespace: redhat-oadp-operator
spec:
  installPlanApproval: Automatic
  name: redhat-oadp-operator
  source: prega-operator-index
  sourceNamespace: openshift-marketplace
  channel: stable
